[build-system]
requires = [
    "setuptools", "wheel", 
    "torch==1.11.0; python_version=='3.9'",
    "torchvision>=0.9.1; python_version=='3.9'",
    "imageio", "imageio-ffmpeg", "matplotlib",
    "configargparse", "tensorboard>=2.0", "tqdm", "opencv-python"
]